code/app/src/main/res/drawable/rounded_popup.xml, code/app/src/main/res/layout/photo_access_permission.xml, code/app/src/main/res/values/strings.xml
=> Photo pop up fragments

code/app/build.gradle.kts, code/app/src/androidTest/java/com/example/superior_intelligence/TestPhotoActivity.java, code/app/src/main/AndroidManifest.xml, code/app/src/main/java/com/example/superior_intelligence/PhotoActivity.java, code/app/src/main/res/layout/photo_access_permission.xml, code/app/src/main/res/layout/photo_add.xml, code/app/src/main/res/values/strings.xml, code/app/src/main/res/xml/file_paths.xml, code/gradle/libs.versions.toml
- Camera button working, If you press it, a permissions window will pop up. Then allow you to take your photo.
- Upload button working, if you press it, a permissions window will pop up. Then allow you to upload your photo from gallery
- Set up a pop-up warning if your photo is larger then a specific amount of bytes
- Created tests for all non-android built-in functions.
=> Camera functionality

code/app/src/main/res/layout/map.xml, code/app/src/main/res/values/strings.xml
create map.xml
changes in strings.xml
=> 47-the-system-must-display-each-mood-events-emotional-state-and-the-associated-username-on-a-map

code/app/src/main/res/layout/create_mood_main.xml, code/app/src/main/res/values/strings.xml
=> 69 020401 social situation drop down list

code/app/src/main/java/com/example/superior_intelligence/CreateAccountActivity.java, code/app/src/main/java/com/example/superior_intelligence/LoginPageActivity.java, code/app/src/main/java/com/example/superior_intelligence/MainActivity.java, code/app/src/main/res/layout/mood_events_list.xml, code/app/src/main/res/values/strings.xml
Full login UI. User database not included.
=> Full login UI

code/app/src/main/java/com/example/superior_intelligence/MoodCreateAndEditActivity.java, code/app/src/main/res/layout/creating_new_mood_event.xml, code/app/src/main/res/layout/emotional_state_options.xml, code/app/src/main/res/layout/selected_emotional_state.xml, code/app/src/main/res/values/colors.xml, code/app/src/main/res/values/strings.xml
…situations in MoodCreateAndEditActivity
=> Implemented dropdown functionalities for emotional states and social situations in MoodCreateAndEditActivity

code/app/build.gradle.kts, code/app/src/main/java/com/example/superior_intelligence/HomePageActivity.java, code/app/src/main/java/com/example/superior_intelligence/Mood.java, code/app/src/main/java/com/example/superior_intelligence/MoodArrayAdapter.java, code/app/src/main/java/com/example/superior_intelligence/MoodEventTitleFragment.java, code/app/src/main/res/layout/mood_title_fragment.xml, code/gradle/libs.versions.toml
- Created MoodEventTitleFragment for a popup to enter the title
- When user enter title and click continue it should take user to MoodCreateAndEditActivity
- MoodArrayAdapter was created, more attributes to be added to Mood class
- DocumentReference and database stuff were set up in HomePageActivity but they are commented out since not fully functioning yet
=> Mood event database

code/app/src/main/AndroidManifest.xml, code/app/src/main/java/com/example/superior_intelligence/CreateAccountActivity.java, code/app/src/main/java/com/example/superior_intelligence/HomeActivity.java, code/app/src/main/java/com/example/superior_intelligence/LoginPageActivity.java, code/app/src/main/java/com/example/superior_intelligence/MoodCreateAndEditActivity.java, code/app/src/main/java/com/example/superior_intelligence/PhotoActivity.java, code/app/src/main/java/com/example/superior_intelligence/ProfileActivity.java
Made is so the we can nagivate between the activities we have so far
=> set up buttons to go back and forth between current activities

code/app/src/main/java/com/example/superior_intelligence/Event.java, code/app/src/main/java/com/example/superior_intelligence/EventAdapter.java, code/app/src/main/java/com/example/superior_intelligence/HomeActivity.java, code/app/src/main/java/com/example/superior_intelligence/MoodCreateAndEditActivity.java, code/app/src/main/res/layout/creating_new_mood_event.xml, code/app/src/main/res/values/strings.xml
whoever works on the next part here are the issues/what still needs to be done
=> 150 create mood event

code/app/src/androidTest/java/com/example/superior_intelligence/TestMoodCreateAndEditActivity.java, code/app/src/androidTest/java/com/example/superior_intelligence/us010101.java, code/app/src/androidTest/java/com/example/superior_intelligence/us010201.java, code/app/src/main/java/com/example/superior_intelligence/Event.java, code/app/src/main/java/com/example/superior_intelligence/MoodCreateAndEditActivity.java, code/app/src/test/java/com/example/superior_intelligence/TestMoodCreateAndEditActivity.java
- did US010101 intent case
- did US010201 intent case
- did some TestMoodCreateEditActivity test cases for helper functions
=> some mood story tests

code/app/src/androidTest/java/com/example/superior_intelligence/us020401.java
- did the intent case for user story 020401
=> us020401 intent case

code/app/src/androidTest/java/com/example/superior_intelligence/us020101.java, code/app/src/main/java/com/example/superior_intelligence/MoodCreateAndEditActivity.java, code/app/src/main/res/layout/creating_new_mood_event.xml
- did the us020101 intent case
=> finished other details user case

code/app/src/main/java/com/example/superior_intelligence/EventDetailsActivity.java
javadoc added to edit eventdetailsactivity.
=> 124 user data base

code/app/src/main/java/com/example/superior_intelligence/MoodCreateAndEditActivity.java, code/app/src/main/res/layout/creating_new_mood_event.xml
=> 194 new story us 020101

code/app/src/main/java/com/example/superior_intelligence/Database.java, code/app/src/main/java/com/example/superior_intelligence/Event.java, code/app/src/main/java/com/example/superior_intelligence/EventDetailsActivity.java
=> 4 moods us 010601

code/app/src/main/java/com/example/superior_intelligence/DeleteMoodFragment.java, code/app/src/main/java/com/example/superior_intelligence/EventDetailsActivity.java, code/app/src/main/res/layout/delete_mood_fragment.xml, code/app/src/main/res/values/themes.xml
- Can now delete mood from database
- Dialog pop up to confirm when user click delete
- Fully done
=> Delete mood fully implemented with dialog to confirm delete

code/app/src/main/java/com/example/superior_intelligence/NotificationAdapter.java, code/app/src/main/java/com/example/superior_intelligence/Userbase.java
Finished us050101 and us050102
=> notifications work with database

code/app/src/main/java/com/example/superior_intelligence/OtherUserProfileActivity.java, code/app/src/main/java/com/example/superior_intelligence/Userbase.java
- fixed the bug where notifications in the database wont delete
- made it so unfollowing works
=> Following logic cleanup and tweaks

code/app/src/main/java/com/example/superior_intelligence/Comment.java, code/app/src/main/java/com/example/superior_intelligence/CommentsAdapter.java, code/app/src/main/java/com/example/superior_intelligence/Database.java, code/app/src/main/java/com/example/superior_intelligence/Event.java, code/app/src/main/java/com/example/superior_intelligence/EventDetailsActivity.java, code/app/src/main/java/com/example/superior_intelligence/HomeActivity.java, code/app/src/main/java/com/example/superior_intelligence/LoginPageActivity.java, code/app/src/main/java/com/example/superior_intelligence/RecentMoodEventRepository.java, code/app/src/main/java/com/example/superior_intelligence/User.java, code/app/src/main/res/layout/comment_item.xml, code/app/src/main/res/layout/event_details.xml, code/app/src/main/res/layout/login_page.xml, code/app/src/main/res/layout/others_event_details.xml
I implemented the commenting logic more with the ui, and completely with the database, I also did a side quested and fixed a bug in login (for michael to approve)
=> 218 comment linked to database

code/app/src/main/java/com/example/superior_intelligence/Event.java, code/app/src/main/java/com/example/superior_intelligence/EventAdapter.java, code/app/src/main/java/com/example/superior_intelligence/EventDetailsActivity.java, code/app/src/main/java/com/example/superior_intelligence/MoodCreateAndEditActivity.java, code/app/src/main/java/com/example/superior_intelligence/PostStatusFragment.java, code/app/src/main/res/layout/event_details.xml, code/app/src/main/res/layout/list_event.xml
- can now see public/priv status in event detail page
- can click on status to change 
- bug back button from explore page to home page: fixed
- if post is from user you follow, it will take you back to followed page
=> 227 new story 010701: Add edit public/priv status to editEvent & Fix back button bug from eventDetail page

code/app/src/main/java/com/example/superior_intelligence/HomeActivity.java
Created a pop-up menu so that when you click on 'filter by emotion' from the spinner it brings up a pop-upmenu taht allows you to select multiple emotions to filter from and then displays emotions that fit the filter(s)
=> Created and formulated the needed filters for emotions.

code/app/src/main/java/com/example/superior_intelligence/HomeActivity.java, code/app/src/main/res/menu/filter_menu.xml
implement filterPostsByMood from filterMyPostsByMood to make it a common function, filter by emotional state now work on both followed and myPosts tab
=> filter followed posts by emotional state

code/app/build.gradle.kts, code/app/src/main/java/com/example/superior_intelligence/MoodMap.java, code/app/src/main/res/layout/event_popup.xml
now the map shows markers from the retrieved location data, filtering the events works (except 12 hours ago), markers show event details.
=> mood map with markers and retrieving location data

code/app/src/main/java/com/example/superior_intelligence/HomeActivity.java
Change color of dialog and button color of filter by emotional state dialog
=> Filter by emotional state dialog theme change

code/app/src/main/java/com/example/superior_intelligence/HomeActivity.java, code/app/src/main/res/layout/filter_popup_menu.xml
- change filter menu from spinner to PopupMenu
- bug where "select filter" was floating when closing filter button is now fixed
- add "Show 3 recent posts" option to filter menu when user is on followed tab
- user can now select to see most 3 recent posts
=> Update filter menu to popUpMenu and add recent3 posts of following list

code/app/src/main/java/com/example/superior_intelligence/MoodMap.java
5km radius is being checked now for location data
=> 5km radius is being checked

code/app/src/androidTest/java/com/example/superior_intelligence/us040201.java, code/app/src/main/java/com/example/superior_intelligence/Database.java, code/app/src/main/java/com/example/superior_intelligence/Event.java, code/app/src/main/java/com/example/superior_intelligence/Mapper.java
- fixed Mapper.java is not setting and retrieving post's user correctly
- fixed Event.java to correctly get and set user
- testcase for 04.02.01 filtering recent week for myposts [done]
=> 25 story us 050301

code/app/src/main/java/com/example/superior_intelligence/HomeActivity.java
- add javadoc to HomeActivity class and to functions that are missing description
=> Javadoc HomeActivity

code/app/src/main/java/com/example/superior_intelligence/CreateAccountActivity.java, code/app/src/main/java/com/example/superior_intelligence/HelperClass.java, code/app/src/main/java/com/example/superior_intelligence/HomeActivity.java, code/app/src/main/java/com/example/superior_intelligence/LoginPageActivity.java, code/app/src/main/java/com/example/superior_intelligence/MoodMap.java, code/app/src/main/java/com/example/superior_intelligence/PasswordHasher.java, code/app/src/main/java/com/example/superior_intelligence/ProfileActivity.java, code/app/src/main/java/com/example/superior_intelligence/Userbase.java, code/app/src/main/res/layout/create_account_page.xml, code/app/src/main/res/layout/login_page.xml, code/app/src/main/res/layout/map.xml, code/app/src/main/res/layout/notifications.xml
Implement password login, profile updates, moodmap, and fix incoming_requests in profile XML
- Integrated SHA-256 hashing for secure password storage and verification.
- Updated CreateAccountActivity and LoginPageActivity to hash and compare passwords.
- Added functionality for users to update their profile photo and name.
- Fully implemented moodmap feature.
- Fixed layout issues with incoming_requests in profile XML.
=> 22 story us060401

code/app/src/androidTest/java/com/example/superior_intelligence/us040201.java, code/app/src/main/java/com/example/superior_intelligence/HomeActivity.java
- Add pop up menu instead of spinner for filter button 
- Add recentThree() function that was lost
=> Fix filter pop up menu again

code/app/src/androidTest/java/com/example/superior_intelligence/us010701.java
=> did test case for us010701

code/app/src/androidTest/java/com/example/superior_intelligence/us040201.java
- UI test 040201 is now pass with the new password implementation
=> Fix ui 040201 with password

code/app/src/androidTest/java/com/example/superior_intelligence/TestOfflineActivity.java
fixed 2nd test case in TestOfflineActivity
=> 20 us 070101

code/app/src/androidTest/java/com/example/superior_intelligence/us050401.java
- 050401 filter  recent week for following posts
=> test case 050401 working

code/app/src/androidTest/java/com/example/superior_intelligence/TestOfflineActivity.java, code/app/src/androidTest/java/com/example/superior_intelligence/us030101.java
Fixed us030101 UI test to accommodate implementation of password. Small fix to OfflineBehavior test.
=> UI test fix for us030101:

code/app/src/androidTest/java/com/example/superior_intelligence/us050301.java
- UI test for 050301 filtering 3 most recent posts from people you followed
- Wrong role of loggedInUser and followedUser in 050401 test is fixed
=> UI test for 050301 Recent 3 Posts and change usernames in 050401

code/app/src/androidTest/java/com/example/superior_intelligence/us040401.java, code/app/src/main/java/com/example/superior_intelligence/HomeActivity.java, code/app/src/main/res/values/ids.xml
- Set EditText's id for filterByText dialog for ui testing when clicking to add text
- Add ids.xml file for the EditText id
- FInish UI test case for US 04.04.01 (testing search by full phrase, word, partial word, empty keyword)
=> 7 us 040401 testcase

code/app/src/androidTest/java/com/example/superior_intelligence/us040201.java, code/app/src/androidTest/java/com/example/superior_intelligence/us050501.java
- ui test for us 050501 filtering mood following list is now complete
- update javadoc for test us 040201
=> Us 050501 filter mood following test

code/app/build.gradle.kts, code/app/src/androidTest/java/com/example/superior_intelligence/DatabaseTest.java
Unit test for database is done, including javadocs.
=> Unit test for database

code/app/src/androidTest/java/com/example/superior_intelligence/us050301.java, code/app/src/androidTest/java/com/example/superior_intelligence/us050601.java
- add test case for 050601 filtering by text for following post
- add javadoc to test us050301
=> 050601 test case

code/app/src/main/java/com/example/superior_intelligence/EventDetailsActivity.java, code/app/src/main/java/com/example/superior_intelligence/EventManager.java, code/app/src/main/java/com/example/superior_intelligence/HomeActivity.java, code/app/src/main/java/com/example/superior_intelligence/HomeManager.java, code/app/src/main/java/com/example/superior_intelligence/MoodCreateAndEditActivity.java, code/app/src/test/java/com/example/superior_intelligence/EventDetailsTest.java, code/app/src/test/java/com/example/superior_intelligence/HomeTest.java, code/app/src/test/java/com/example/superior_intelligence/MoodCreateTest.java
Hometest+eventdetailstest+createeventtest
=> Hometest+eventdetailstest+createeventtest

code/app/src/androidTest/java/com/example/superior_intelligence/TestLoginPageActivity.java, code/app/src/main/java/com/example/superior_intelligence/LoginPageActivity.java
Though it is a unit test, had to put it in androidTest due to UI components being present in LoginPageActivity.
=> Unit test for LoginPageActivity

code/app/src/androidTest/java/com/example/superior_intelligence/UserStory04_01_01Test.java, code/app/src/main/java/com/example/superior_intelligence/FirestoreIdlingResource.java, code/gradle/libs.versions.toml
created UI test cases for userstory 04.01.01 (issue number 5) as well as its sub issues (04.01.01 issue number 111 and 04.01.02 issue number 112).
=> Test cases for US 04.01.01 and its respective sub issues

code/app/src/androidTest/java/com/example/superior_intelligence/UserStory04_03_01Test.java
test file named UserStory04_03_01Test.java that tests user story 04.03.01 and its sub issue which tests for filtering 'MYMOODS' by emotions by first logging in anonymously and then creating two mood events with differet moods and then filters for one of those moods and checks to see if that mood event remains and if the other one is removed from view.
=> made the test file for the testing of user story 04.03.03 (issue number 6) and its sub issue (issue number 116)

code/app/src/androidTest/java/com/example/superior_intelligence/UserStory04_03_01Test.java
properly implemented tearDown() and made it so that the test runs on the fb emulator rather than the actual live fb db console
=> Fixed issues with 04.03.01 UI testing

code/app/src/androidTest/java/com/example/superior_intelligence/us060201_060301_060401.java, code/app/src/main/java/com/example/superior_intelligence/MoodMap.java
- javadoc for moodmap test
- javadoc for moopmap class
=> Javadoc moodMap
